// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    D2Item: typeof import('./src/components/D2Item.vue')['default']
    D2ItemRow: typeof import('./src/components/D2ItemRow.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    MenuNode: typeof import('./src/components/MenuNode.vue')['default']
    TopNItemsPanel: typeof import('./src/components/TopNItemsPanel.vue')['default']
  }
}
